const GET_USER = 'GET_USER';
const DELETE_USER = 'DELETE_USER';
const IS_AUTH = 'IS_AUTH';
const IS_UNAUTH= 'IS_UNAUTH'
const TRY_RESET_PASSWORD = 'TRY_RESET_PASSWORD'
const PASSWORD_IS_RESET = 'PASSWORD_IS_RESET'

export {GET_USER, DELETE_USER, IS_AUTH ,IS_UNAUTH, TRY_RESET_PASSWORD, PASSWORD_IS_RESET}
