const GET_INGREDIENTS = 'GET_INGREDIENTS';
const GET_INGREDIENT_FOR_BURGER = 'GET_INGREDIENT_FOR_BURGER';
const INGREDIENT_DETAILS = 'INGREDIENT_DETAILS';
const DETAILS_REMOVE = 'DETAILS_REMOVE';
const ORDER = 'ORDER';

export {GET_INGREDIENTS, GET_INGREDIENT_FOR_BURGER, INGREDIENT_DETAILS, DETAILS_REMOVE, ORDER}
