const WS_OPENED = 'WS_OPENED';
const WS_CLOSED = 'WS_CLOSED';
const WS_CLOSED_WITH_ERROR = 'WS_CLOSED_WITH_ERROR';
const WS_GET_DATA = 'WS_GET_DATA';

export {WS_CLOSED, WS_OPENED, WS_CLOSED_WITH_ERROR, WS_GET_DATA}
