const WS_OPENED = 'WS_OPENED';
const WS_CLOSED = 'WS_CLOSED';
const WS_CLOSED_WITH_ERROR = 'WS_CLOSED_WITH_ERROR';
const WS_GET_DATA = 'WS_GET_DATA';
const WS_IS_OPEN = 'WS_IS_OPEN';
const WS_IS_CLOSE = 'WS_IS_CLOSE'

export {WS_CLOSED, WS_OPENED, WS_CLOSED_WITH_ERROR, WS_GET_DATA, WS_IS_OPEN, WS_IS_CLOSE}
