const WS_AUTH_OPENED = 'WS_AUTH_OPENED';
const WS_AUTH_CLOSED = 'WS_AUTH_CLOSED';
const WS_AUTH_CLOSED_WITH_ERROR = 'WS_AUTH_CLOSED_WITH_ERROR';
const WS_AUTH_GET_DATA = 'WS_AUTH_GET_DATA';
const WS_AUTH_START ='WS_AUTH_START'

export {WS_AUTH_CLOSED, WS_AUTH_OPENED, WS_AUTH_CLOSED_WITH_ERROR, WS_AUTH_GET_DATA, WS_AUTH_START}
